/**
 * @fileoverview gRPC-Web generated client stub for anagramService
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: anagram.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.anagramService = require('./anagram_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.anagramService.AnagramServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.anagramService.AnagramServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.anagramService.AnagramRequest,
 *   !proto.anagramService.AnagramResponse>}
 */
const methodDescriptor_AnagramService_GetAnagramsByTitle = new grpc.web.MethodDescriptor(
  '/anagramService.AnagramService/GetAnagramsByTitle',
  grpc.web.MethodType.UNARY,
  proto.anagramService.AnagramRequest,
  proto.anagramService.AnagramResponse,
  /**
   * @param {!proto.anagramService.AnagramRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.anagramService.AnagramResponse.deserializeBinary
);


/**
 * @param {!proto.anagramService.AnagramRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.anagramService.AnagramResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.anagramService.AnagramResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.anagramService.AnagramServiceClient.prototype.getAnagramsByTitle =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/anagramService.AnagramService/GetAnagramsByTitle',
      request,
      metadata || {},
      methodDescriptor_AnagramService_GetAnagramsByTitle,
      callback);
};


/**
 * @param {!proto.anagramService.AnagramRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.anagramService.AnagramResponse>}
 *     Promise that resolves to the response
 */
proto.anagramService.AnagramServicePromiseClient.prototype.getAnagramsByTitle =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/anagramService.AnagramService/GetAnagramsByTitle',
      request,
      metadata || {},
      methodDescriptor_AnagramService_GetAnagramsByTitle);
};


module.exports = proto.anagramService;

